export const ADDPOST_REQUEST = '@@post/ADDPOST_REQUEST'
export const ADDPOST_SUCCESS = '@@post/ADDPOST_SUCCESS'
export const ADDPOST_ERROR = '@@post/ADDPOST_ERROR'

export const ADDCOMMENT_REQUEST = '@@comment/ADDCOMMENT_REQUEST'
export const ADDCOMMENT_SUCCESS = '@@comment/ADDCOMMENT_SUCCESS'
export const ADDCOMMENT_ERROR = '@@comment/ADDCOMMENT_ERROR'

export const FETCH_POSTS_REQUEST = '@@post/FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = '@@post/FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = '@@post/FETCH_POSTS_ERROR'

export const FETCH_USER_POSTS_REQUEST = '@@post/FETCH_USER_POSTS_REQUEST'
export const FETCH_USER_POSTS_SUCCESS = '@@post/FETCH_USER_POSTS_SUCCESS'
export const FETCH_USER_POSTS_ERROR = '@@post/FETCH_USER_POSTS_ERROR'

export const FETCH_MORE_POSTS_REQUEST = '@@post/FETCH_MORE_POSTS_REQUEST'
export const FETCH_MORE_POSTS_SUCCESS = '@@post/FETCH_MORE_POSTS_SUCCESS'
export const FETCH_MORE_POSTS_ERROR = '@@post/FETCH_MORE_POSTS_ERROR'

export const FETCH_POST_BY_ID_REQUEST = '@@post/FETCH_POST_BY_ID_REQUEST'
export const FETCH_POST_BY_ID_SUCCESS = '@@post/FETCH_POST_BY_IDS_SUCCESS'
export const FETCH_POST_BY_ID_ERROR = '@@post/FETCH_POST_BY_IDS_ERROR'

export const DELETE_POST_BY_ID_REQUEST = '@@post/DELETE_POST_BY_ID_REQUEST'
export const DELETE_POST_BY_ID_SUCCESS = '@@post/DELETE_POST_BY_ID_SUCCESS'
export const DELETE_POST_BY_ID_ERROR = '@@post/DELETE_POST_ERROR'

export const RESET_POSTS = '@@post/RESET_POSTS'

export const LIKE_REQUEST = '@@post/LIKE_REQUEST'
export const LIKE_SUCCESS = '@@post/LIKE_SUCCESS'
export const LIKE_ERROR = '@@post/LIKE_ERROR'

export const UNLIKE_REQUEST = '@@post/UNLIKE_REQUEST'
export const UNLIKE_SUCCESS = '@@post/UNLIKE_SUCCESS'
export const UNLIKE_ERROR = '@@post/UNLIKE_ERROR'

export const FETCH_POSTS_BY_USER_REQUEST = '@@post/FETCH_POSTS_BY_USER_REQUEST'
export const FETCH_POSTS_BY_USER_SUCCESS = '@@post/FETCH_POSTS_BY_USER_SUCCESS'
export const FETCH_POSTS_BY_USER_ERROR = '@@post/FETCH_POSTS_BY_USER_ERROR'